# Cytoscape Automation in R using Rcy3

## Instructor(s) name(s) and contact information

* Ruth Isserlin <ruth.isserlin@utoronto.ca>
* Brendan Innes <brendan.innes@mail.utoronto.ca>
* Jeff Wong <jvwong@gmail.com> 
* Gary Bader <gary.bader@utoronto.ca>

## Workshop Description

Cytoscape is one of the most popular applications for network analysis and visualization. In this workshop, we will demonstrate new capabilities to integrate Cytoscape into programmatic workflows and pipelines using R. We will begin with an overview of network biology themes and concepts, and then we will translate these into Cytoscape terms for practical applications. The bulk of the workshop will be a hands-on demonstration of accessing and controlling Cytoscape from R to perform a network analysis of tumor expression data.

### Pre-requisites

#### Workshop prerequisites:
* Basic knowledge of R syntax
* Basic knowledge of Cytoscape software
* Familiarity with network biology concepts

#### Background:
* “How to visually interpret biological data using networks.” Merico D, Gfeller D, Bader GD. Nature Biotechnology 2009 Oct 27, 921-924 - http://baderlab.org/Publications?action=AttachFile&do=view&target=2009_Merico_Primer_NatBiotech_Oct.pdf
* “CyREST: Turbocharging Cytoscape Access for External Tools via a RESTful API”. Keiichiro Ono, Tanja Muetze, Georgi Kolishovski, Paul Shannon, Barry Demchak.F1000Res. 2015 Aug 5;4:478. - https://f1000research.com/articles/4-478/v1

### Workshop Participation
Participants are required to bring a laptop with Cytoscape, R, and RStudio installed.  Installation instructions will be provided in the weeks preceding the workshop.  The workshop will consist of a lecture and lab.

### R / Bioconductor packages used
* RCy3

### Time outline

| Activity                                       | Time |
|------------------------------------------------|------|
| Introduction                                   | 15m  |
| Driving Cytoscape from R                       | 15m  |
| Creating, retrieving and manipulating networks | 15m  |
| Summary                                        | 10m  |


## Workshop goals and objectives

### Learning goals

* Know when and how to use Cytoscape in your research area
* Generalize network analysis methods to multiple problem domains
* Integrate Cytoscape into your bioinformatics pipelines

### Learning objectives

* Programmatic control over Cytoscape from R
* Publish, share and export networks
