# Maintaining your Bioconductor package

## Instructor name and contact information

* Nitesh Turaga ^[Roswell Park Comprehensive Cancer Center, Buffalo, NY] (<nitesh.turaga@roswellpark.org>)

## Workshop Description:

Once an R package is accepted into Bioconductor, maintaining it is an active responsibility undertaken by the package developers and maintainers. In this short workshop, we will cover how to maintain a Bioconductor package using existing infrastructure. Bioconductor hosts a range of tools which maintainers can use such as daily build reports, landing page badges, RSS feeds, download stats, support site questions, and the bioc-devel mailing list. Some packages have their own continuous integration hook setup on their github pages which would be an additional tool maintainers can use to monitor their package. We will also highlight one particular git practice which need to be done while updating and maintaining your package on out git system.

## Pre-requisites:

Accepted Bioconductor package or plans to contribute a Bioconductor package in the future.

## Participation:

Students will be expected to follow along with their laptops if they choose to, although it is not needed. 

## Time outline: 50 mins short workshop

Introduction: 10 mins
Why maintain your package
Infrastructure used for maintenance
Outline how to use infrastructure: 35 mins
	Build report
	Landing page badges
	RSS feeds
	Download statistics
	Support site, Github issues, Bioc-devel mailing list
Sync package with Github / Bioconductor before every change
	GitHub + webhooks
Round up of resources available: 5 mins

## Workshop goals and objectives:

* Gain knowledge of how to track Bioconductor packages via download statistics, RSS feeds.
* Understand the importance of supporting their user community and how to do so using the support site and bioc-devel mailing list.
* Maintain their package and fix bugs using build reports, continuous integration tools.
* Update their package consistently on both Github and Bioconductor private git server.  
